services:
  db:
    image: postgres:18
    container_name: kanban-axisor-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  redis:
    image: redis:7
    container_name: kanban-axisor-redis
    restart: always
    ports:
      - '6379:6379'

  minio:
    image: minio/minio
    container_name: kanban-axisor-minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${S3_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${S3_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
  minio-data:
